# Generated by Django 5.0.1 on 2024-02-08 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servicesModel',
            fields=[
                ('services_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iconUrl', models.CharField(max_length=100)),
                ('iconText', models.CharField(max_length=100)),
                ('iconHeight', models.IntegerField()),
                ('iconWidth', models.IntegerField()),
            ],
        ),
    ]
